export const USERS = [
    {
        roleKey: "EMPEROR",
        roleTitle: "Emperor",
        callSign: "Darth Sidious",
        name: "Emperor Palpatine",
        email: "palpatine@imperial.hr",
        password: "Imperial#1",
        allowed: 30,
        used: 5,
        workHours: 165,
    },
    {
        roleKey: "LORD",
        roleTitle: "Lord",
        callSign: "Lord Vader",
        name: "Darth Vader",
        email: "vader@imperial.hr",
        password: "Imperial#2",
        allowed: 30,
        used: 7,
        workHours: 165,
    },
    {
        roleKey: "TROOPER",
        roleTitle: "Trooper",
        callSign: "TK-421",
        name: "Stormtrooper",
        email: "trooper@imperial.hr",
        password: "Imperial#3",
        allowed: 30,
        used: 5,
        workHours: 149,
    },
];
